// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/user/refresh": {
            "post": {
                "description": "Get a new access token using a valid refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Refresh the access token",
                "parameters": [
                    {
                        "description": "Access token object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.Token"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Token"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPError"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPError"
                        }
                    }
                }
            }
        },
        "/user/register": {
            "post": {
                "description": "Register a new user using his email, username and password. Returns his ID, email, username, verifiedEmail boolean variable and role",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "Register a new user",
                "parameters": [
                    {
                        "description": "User registration body object",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UserRegister"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.UserRegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.HTTPError"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AuthTokens": {
            "type": "object",
            "properties": {
                "access": {
                    "description": "Access token",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Token"
                        }
                    ]
                },
                "refresh": {
                    "description": "Refresh token",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.Token"
                        }
                    ]
                }
            }
        },
        "dto.HTTPError": {
            "type": "object",
            "properties": {
                "code": {
                    "description": "HTTP error code",
                    "type": "integer",
                    "example": 400
                },
                "message": {
                    "description": "Error message",
                    "type": "string",
                    "example": "you are retard"
                }
            }
        },
        "dto.Token": {
            "type": "object",
            "properties": {
                "expires": {
                    "description": "Token expiration time in ISO 8601 format",
                    "type": "string",
                    "example": "2024-12-08T10:00:12.961568771Z"
                },
                "token": {
                    "description": "Token string itself",
                    "type": "string",
                    "example": "somelong.token.string"
                }
            }
        },
        "dto.UserRegister": {
            "type": "object",
            "required": [
                "email",
                "password",
                "username"
            ],
            "properties": {
                "email": {
                    "description": "Required, email must be valid",
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "password": {
                    "description": "Required, password must meet certain requirements: must has upper case letters, lower case letters and digits",
                    "type": "string",
                    "example": "Password1234"
                },
                "username": {
                    "description": "Required, user's username",
                    "type": "string",
                    "example": "linuxflight"
                }
            }
        },
        "dto.UserRegisterResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "description": "Two JWT tokens: Access token and Refresh token",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.AuthTokens"
                        }
                    ]
                },
                "user": {
                    "description": "User object",
                    "allOf": [
                        {
                            "$ref": "#/definitions/dto.UserReturn"
                        }
                    ]
                }
            }
        },
        "dto.UserReturn": {
            "type": "object",
            "properties": {
                "email": {
                    "description": "User's email",
                    "type": "string",
                    "example": "example@gmail.com"
                },
                "id": {
                    "description": "User ID",
                    "type": "string",
                    "example": "123"
                },
                "role": {
                    "description": "User's role (e.g. \"Client\", \"Manager\" etc)",
                    "type": "string",
                    "example": "manager"
                },
                "username": {
                    "description": "User's username",
                    "type": "string",
                    "example": "linuxflight"
                },
                "verified_email": {
                    "description": "Boll variable showing, whether user's email is verified or not",
                    "type": "boolean",
                    "example": true
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3000",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "WebTemplate API",
	Description:      "This is a webtemplate API that contains project dir structure, JWT auth, basic user entitites and can be further expanded.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
